Interactive list
bizip/todo-list pull request #3
Opened 2022-05-06 16:04 UTC by bizip

**What does this PR do?**

- Add interactive list functionality

**Description of Task to be completed**

All tasks related to deployment are completed 
**How should this be manually tested?**

1. Clone this repository and switch to feature-interactive-list`
2. Install all required dependencies `npm install`
3. run `npm run dev`

2022-05-06 17:20 UTC, bizip commented
> # Status: Required Changes ♻️
> Hi @bizip 👋🏾,
> 
> ![Alt Text](https://camo.githubusercontent.com/fa6dab5044e2d5c94cce5c80dfeecafbfdfa93891575c1ecd80c828be68110d4/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f7a35634e716246624d544441342f3230302e676966)
> 
> Good job so far! 👏🏾 There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> ✔️ All linter checks pass
> 
> ## Required Changes ♻️
> * [ ]  Kindly check your application, I am not able to add to the list or remove from the todo. Your functions do not seem to be connected or working.
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me `@chaw-bot` in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Hello @chaw-bot, oh sorry but on my side it is working fine What is the issue exactly?

2022-05-06 17:21 UTC, bizip commented
Hello @chaw-bot, oh sorry but on my side it is working fine What is the issue exactly?

2022-05-06 22:08 UTC, zieeco requested changes
Hi @bizip 


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 22:08 UTC, zieeco commented on src/index.js
>  });
**[REQUIRE CHANGES]**

- [ ] Hey, there's an issue that you need to fix. Kindly use the `array. filter method` here as the effect of this is clearing your localStorage leaving your UI with no effect except the user reloads your app. i.e, both tasks completed and not completed are cleared once a user clicks on the clear completed button.
You can create a function to clear the completed task using the `array.filter` method. e.g:

```
const clearAllCompletedTask = () => {
   yourArray = yourArray.filter((todo) => !todo.completed);
  
  // localStorage.setItem('X', JSON.stringify(yourArray));
  // call your display method 
 }
```

- Your checkbox gets updated in the localStorage if checked but on reload, It loses its states as been checked. Kindly update it so that when a user clicks a checkbox, then it should not lose it state when they refresh your app.

2022-05-07 06:12 UTC, bizip commented on src/index.js
>  });
Thank you, the feed back is clear

2022-05-07 15:55 UTC, gtekle approved these changes
Hi @bizip :wave:, 

# STATUS: APPROVED :clap: :clap: :clap: 🎉 🎉 🎉 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![approved-stamp-02](https://user-images.githubusercontent.com/44057863/167262053-b5cc021b-9216-4f5d-9d34-e08dd7b27732.gif)

## Highlights
:heavy_check_mark: Well organized and clean code
:heavy_check_mark: Professional readme
:heavy_check_mark: Implemented all requirements for the milestone

## Optional suggestions

- [ Optional ] It would be good if you add some styling to your buttons to indicate that they are clickable by adding (`cursor: pointer;`) css rule for better user experience.

- [ Optional] It is good if you add the add task button for better user experience as in the demo todo-list project. 
![todo-list-impl](https://user-images.githubusercontent.com/44057863/167261986-afa77066-7f08-49be-81ad-df1814835569.png)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-07 16:36 UTC, bizip commented
Thank you @gtekle, I am going to work on that as soon as possible.

2022-05-09 06:46 UTC, merged